name: KanjiQuest
options:
  bundleIdPrefix: com.jworks.kanjiquest
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "2"  # iPad only

configs:
  Debug: debug
  Release: release

targets:
  KanjiQuest:
    type: application
    platform: iOS
    configFiles:
      Debug: KanjiQuest.xcconfig
      Release: KanjiQuest.xcconfig

    sources:
      - path: KanjiQuest
        excludes:
          - "**/.DS_Store"

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jworks.kanjiquest.ipad
        INFOPLIST_FILE: KanjiQuest/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        # Inject xcconfig values into Info.plist
        SUPABASE_URL: $(SUPABASE_URL)
        SUPABASE_ANON_KEY: $(SUPABASE_ANON_KEY)
        SUPABASE_SERVICE_ROLE_KEY: $(SUPABASE_SERVICE_ROLE_KEY)
        GEMINI_API_KEY: $(GEMINI_API_KEY)
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
          SWIFT_COMPILATION_MODE: wholemodule

    dependencies:
      - framework: ../shared-core/build/XCFrameworks/release/SharedCore.framework
        embed: true

    preBuildScripts:
      - name: "Build SharedCore XCFramework"
        script: |
          # Only build if XCFramework doesn't exist or source changed
          XCFRAMEWORK_DIR="${PROJECT_DIR}/../shared-core/build/XCFrameworks/release"
          if [ ! -d "$XCFRAMEWORK_DIR/SharedCore.framework" ]; then
            cd "${PROJECT_DIR}/.."
            ./gradlew :shared-core:assembleSharedCoreReleaseXCFramework
          fi
        basedOnDependencyAnalysis: false

    postCompileScripts:
      - name: "Copy Database"
        script: |
          # Copy pre-built kanji database to app bundle
          DB_SOURCE="${PROJECT_DIR}/../android-app/src/main/assets/kanjiquest.db"
          DB_DEST="${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/kanjiquest.db"
          if [ -f "$DB_SOURCE" ]; then
            cp "$DB_SOURCE" "$DB_DEST"
          fi
        basedOnDependencyAnalysis: false

  KanjiQuestTests:
    type: bundle.unit-test
    platform: iOS

    sources:
      - path: KanjiQuestTests

    dependencies:
      - target: KanjiQuest

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jworks.kanjiquest.ipad.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/KanjiQuest.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/KanjiQuest"
        BUNDLE_LOADER: "$(TEST_HOST)"

  KanjiQuestUITests:
    type: bundle.ui-testing
    platform: iOS

    sources:
      - path: KanjiQuestUITests

    dependencies:
      - target: KanjiQuest

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jworks.kanjiquest.ipad.uitests
        TEST_TARGET_NAME: KanjiQuest

schemes:
  KanjiQuest:
    build:
      targets:
        KanjiQuest: all
        KanjiQuestTests: [test]
        KanjiQuestUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - KanjiQuestTests
        - KanjiQuestUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
