name: KanjiQuest
options:
  bundleIdPrefix: com.jworks.kanjiquest
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "21"
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "2"  # iPad only

configs:
  Debug: debug
  Release: release

targets:
  KanjiQuest:
    type: application
    platform: iOS
    configFiles:
      Debug: KanjiQuest.xcconfig
      Release: KanjiQuest.xcconfig

    sources:
      - path: KanjiQuest
        excludes:
          - "**/.DS_Store"
      - path: kanjiquest.db
        buildPhase: resources

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jworks.kanjiquest.ipad
        INFOPLIST_FILE: KanjiQuest/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "2"  # iPad only
        CODE_SIGN_STYLE: Automatic
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        FRAMEWORK_SEARCH_PATHS: $(PROJECT_DIR)/Frameworks
        SUPABASE_URL: $(SUPABASE_URL)
        SUPABASE_ANON_KEY: $(SUPABASE_ANON_KEY)
        SUPABASE_SERVICE_ROLE_KEY: $(SUPABASE_SERVICE_ROLE_KEY)
        GEMINI_API_KEY: $(GEMINI_API_KEY)
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG IPAD_TARGET
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
          SWIFT_COMPILATION_MODE: wholemodule
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: IPAD_TARGET

    dependencies:
      - framework: $(PROJECT_DIR)/Frameworks/SharedCore.xcframework
        embed: true
      - framework: $(PROJECT_DIR)/Frameworks/SharedJapanese.xcframework
        embed: true
      - sdk: libsqlite3.tbd

    preBuildScripts:
      - name: "Stage Database"
        script: |
          # Copy pre-built kanji database to project dir for resource bundling
          DB_DEST="${PROJECT_DIR}/kanjiquest.db"
          DB_SRC="${PROJECT_DIR}/../android-app/src/main/assets/kanjiquest.db"
          if [ ! -f "$DB_DEST" ] && [ -f "$DB_SRC" ]; then
            cp "$DB_SRC" "$DB_DEST"
          fi
        basedOnDependencyAnalysis: false

      - name: "Link SharedCore XCFramework"
        script: |
          # Copy XCFramework to local Frameworks/ if not present
          DEST="${PROJECT_DIR}/Frameworks/SharedCore.xcframework"
          SRC="${PROJECT_DIR}/../shared-core/build/XCFrameworks/release/SharedCore.xcframework"
          if [ ! -d "$DEST" ] && [ -d "$SRC" ]; then
            mkdir -p "${PROJECT_DIR}/Frameworks"
            cp -R "$SRC" "$DEST"
          elif [ ! -d "$DEST" ]; then
            cd "${PROJECT_DIR}/.."
            ./gradlew :shared-core:assembleSharedCoreReleaseXCFramework
            mkdir -p "${PROJECT_DIR}/Frameworks"
            cp -R "$SRC" "$DEST"
          fi
        basedOnDependencyAnalysis: false

  KanjiQuestTests:
    type: bundle.unit-test
    platform: iOS

    sources:
      - path: KanjiQuestTests

    dependencies:
      - target: KanjiQuest

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jworks.kanjiquest.ipad.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/KanjiQuest.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/KanjiQuest"
        BUNDLE_LOADER: "$(TEST_HOST)"

  KanjiQuestUITests:
    type: bundle.ui-testing
    platform: iOS

    sources:
      - path: KanjiQuestUITests

    dependencies:
      - target: KanjiQuest

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jworks.kanjiquest.ipad.uitests
        TEST_TARGET_NAME: KanjiQuest

schemes:
  KanjiQuest:
    build:
      targets:
        KanjiQuest: all
        KanjiQuestTests: [test]
        KanjiQuestUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - KanjiQuestTests
        - KanjiQuestUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release


