name: BrushTest
options:
  bundleIdPrefix: com.jworks.kanjiquest
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "10"
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "2"

targets:
  BrushTest:
    type: application
    platform: iOS

    sources:
      - path: BrushTest

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jworks.kanjiquest.ipad
        INFOPLIST_FILE: BrushTest/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "2"
        CODE_SIGN_STYLE: Automatic
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false

schemes:
  BrushTest:
    build:
      targets:
        BrushTest: all
    run:
      config: Debug
    archive:
      config: Release
